In [ ]:
pip install python-csv

     |████████████████████████████████| 131 kB 8.5 MB/s 
     |████████████████████████████████| 963 kB 47.2 MB/s 
     |████████████████████████████████| 154 kB 57.5 MB/s 
     |████████████████████████████████| 138 kB 49.7 MB/s 
     |████████████████████████████████| 359 kB 61.0 MB/s 
     |████████████████████████████████| 138 kB 70.5 MB/s 
     |████████████████████████████████| 138 kB 52.4 MB/s 
     |████████████████████████████████| 138 kB 59.8 MB/s 
     |████████████████████████████████| 153 kB 56.8 MB/s 
     |████████████████████████████████| 137 kB 57.9 MB/s 
     |████████████████████████████████| 136 kB 51.5 MB/s 
     |████████████████████████████████| 136 kB 56.4 MB/s 
     |████████████████████████████████| 136 kB 58.4 MB/s 
INFO: pip is looking at multiple versions of trio-websocket to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of attrs to determine which version is compatible with

In [ ]:
pip install pandas

In [ ]:
pip install numpy

In [ ]:
pip install estimator

  Created wheel for estimator: filename=estimator-0.0.10-py3-none-any.whl size=7634 sha256=0d6847aa46837ebea085e50271bead89878036d89cc45424b4768fe310525fbc
  Stored in directory: /root/.cache/pip/wheels/8d/c7/fc/4ed1eb1659042c405faeb997f30cad3670a8297335cf758d1b
Successfully built estimator


In [ ]:
pip list

Package                       Version
----------------------------- --------------
absl-py                       1.0.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.2.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.11.4
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.4.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.1.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.2
branca                        0.4.2
bs4                           0.0.1
CacheControl 

In [ ]:
import csv
import pandas as pd
import numpy as np


In [ ]:
data6 = pd.read_csv('drive/MyDrive/SKRIPSI/Data-hasil-stemminglabel.csv',encoding='ISO-8859-1')


In [ ]:
data6

Tweets    Label
0    vaksin asa gigit semut kampung vaksin asa gigi...  Negatif
1    sadar warga republik indonesia hidup damping c...  Positif
2    puluh asn jaring razia vaksin kota subulussala...  Negatif
3    iya deh bangga pure bloood vaksin mah noda pen...  Negatif
4        iya deh insyaallah program vaksin kantor desa  Positif
..                                                 ...      ...
673                  jae habis vaksin tangan sakit gel  Negatif
674                  vaksin keluarga sehat maju jokowi  Positif
675                                             vaksin   Netral
676           suntik vaksin biar kuat fisik lemah hati  Negatif
677      vaksin sakit radang tenggorok plus dada sesak  Negatif

[678 rows x 2 columns]

In [ ]:
#proses TF-IDF
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

tvec = CountVectorizer()
X_cVec = tvec.fit_transform(data6['Tweets'].values.astype('U'))
print(tvec.vocabulary_)
#print(X_cVec)
print(X_cVec.shape)
#print(X_cVec.toarray())

h_tfidf = TfidfTransformer()
x_tfidf = h_tfidf.fit_transform(X_cVec)
print(x_tfidf)
#print(x_tfidf.shape)


{'vaksin': 1395, 'asa': 78, 'gigit': 419, 'semut': 1182, 'kampung': 593, 'megalodon': 801, 'sadar': 1133, 'warga': 1420, 'republik': 1108, 'indonesia': 499, 'hidup': 460, 'damping': 279, 'covid': 267, 'pulih': 1071, 'ri': 1113, 'puluh': 1072, 'asn': 82, 'jaring': 537, 'razia': 1096, 'kota': 671, 'subulussalam': 1250, 'aceh': 5, 'iya': 518, 'deh': 292, 'bangga': 121, 'pure': 1074, 'bloood': 196, 'mah': 749, 'noda': 912, 'penuh': 1002, 'toxin': 1346, 'insyaallah': 507, 'program': 1056, 'kantor': 598, 'desa': 301, 'cepat': 248, 'sembuh': 1180, 'flu': 379, 'senin': 1187, 'mantap': 778, 'nganter': 882, 'pipu': 1025, 'grooming': 425, 'kemarin': 631, 'mager': 748, 'banget': 119, 'enggan': 367, 'tindak': 1330, 'kena': 636, 'jawat': 543, 'awam': 93, 'sayang': 1148, 'tonjol': 1343, 'lengan': 717, 'belah': 153, 'kiri': 657, 'habis': 432, 'amerika': 47, 'serikat': 1199, 'orang': 947, 'dewasa': 305, 'suntik': 1258, 'booster': 207, 'gerai': 414, 'presisi': 1051, 'polres': 1037, 'padang': 954, 'paria

In [ ]:
#tvec.get_feature_names()

In [ ]:
#splitting data

from sklearn.model_selection import train_test_split

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB

X = data6.Tweets
Y = data6.Label
kf = KFold(n_splits=10)
X_array = x_tfidf.toarray()
def cross_val(estimator):
  acc = []
  pcs = []
  rec = []
  for train_index, test_index in kf.split(X_array, Y):
    X_train, X_test = X_array[train_index],  X_array[test_index]
    y_train, y_test = Y[train_index],  Y[test_index]
    model = estimator.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    acc.append(accuracy_score(y_test, y_pred))
    pcs.append(precision_score(y_test, y_pred, average='macro', zero_division=0))
    rec.append(recall_score(y_test, y_pred, average='macro', zero_division=0))
    rec.append(f1_score(y_test, y_pred, average='macro', zero_division=0))
    print(classification_report(y_test, y_pred, zero_division=0))
    print(f'confusion matrix:\n {confusion_matrix(y_test,y_pred)}')
    print('===========================\n')

  print(f'average Akurasi: {np.mean(acc)}')
  print(f'average Precision: {np.mean(pcs)}')
  print(f'average Recall: {np.mean(rec)}')
  print(f'average F1-score: {np.mean(rec)}')




nb = MultinomialNB()
cross_val(nb)


              precision    recall  f1-score   support

     Negatif       0.51      0.84      0.64        25
      Netral       0.80      0.18      0.30        22
     Positif       0.36      0.38      0.37        21

    accuracy                           0.49        68
   macro avg       0.56      0.47      0.43        68
weighted avg       0.56      0.49      0.44        68

confusion matrix:
 [[21  0  4]
 [ 8  4 10]
 [12  1  8]]

              precision    recall  f1-score   support

     Negatif       0.73      0.91      0.81        33
      Netral       0.60      0.19      0.29        16
     Positif       0.59      0.68      0.63        19

    accuracy                           0.68        68
   macro avg       0.64      0.59      0.58        68
weighted avg       0.66      0.68      0.64        68

confusion matrix:
 [[30  1  2]
 [ 6  3  7]
 [ 5  1 13]]

              precision    recall  f1-score   support

     Negatif       0.66      0.93      0.77        29
      Netral   